"""Production one-page workspace assembly for Stage 12.1."""

from __future__ import annotations

from decimal import Decimal

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QApplication, QButtonGroup, QCheckBox, QComboBox, QDialog, QDialogButtonBox,
    QDoubleSpinBox, QFormLayout, QFrame, QGridLayout, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QListView, QListWidget, QPlainTextEdit, QProgressBar,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox, QSplitter, QTabWidget,
    QTableView, QVBoxLayout, QWidget,
)

from larp_audio_mvp.config import ModelSettings, SubtitleSettings, desktop_mvp_pause_settings

from .design.widgets import (
    EditorialPauseChoice,
    Hairline,
    MainHeader,
    SurfaceCard,
    WaveformIcon,
    WorkflowStrip,
)
from .models import SubtitleBlockTableModel, WarningFilterProxyModel
from .path_display import ElidedPathLabel
from .preview.widgets import PreviewPanel


def _title(text: str) -> QLabel:
    label = QLabel(text); label.setObjectName("sectionTitle"); return label


class AdvancedSettingsDialog(QDialog):
    def __init__(self, window) -> None:
        super().__init__(window); self.setWindowIcon(QApplication.windowIcon()); self.setWindowTitle("Advanced Settings"); self.resize(680, 650); self.setMinimumWidth(620)
        layout = QVBoxLayout(self); intro = QLabel("Fine-tune technical processing values. Changes to pause values set Pause style to Custom."); intro.setObjectName("muted"); intro.setWordWrap(True); layout.addWidget(intro)
        tabs = QTabWidget(); layout.addWidget(tabs, 1)
        pause = QWidget(); form = QFormLayout(pause); form.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        form.addRow("Silence threshold", window.pause_threshold); form.addRow("Minimum detected silence", window.minimum_detected_silence); form.addRow("Minimum pause to shorten", window.minimum_pause_to_shorten); form.addRow("Retained pause", window.retained_pause); form.addRow("Maximum removal per pause", window.maximum_pause_removal)
        reset_pause = QPushButton("Reset pause detection to Balanced"); reset_pause.setObjectName("ghostAction"); reset_pause.clicked.connect(lambda: window.set_pause_preset("balanced")); form.addRow(reset_pause); tabs.addTab(pause, "Pause detection")
        speech = QWidget(); speech_form = QFormLayout(speech)
        if window.developer_mode:
            speech_form.addRow("Model size", window.model_name); speech_form.addRow("Device", window.device); speech_form.addRow("Compute precision", window.compute_type); speech_form.addRow("Search beam size", window.recognition_beam_size)
        speech_form.addRow("Language (blank = automatic)", window.recognition_language)
        speech_form.addRow("Speech engine", window.engine_maintenance_status)
        speech_actions = QHBoxLayout(); speech_actions.addWidget(window.check_engine_button); speech_actions.addWidget(window.repair_engine_button); speech_actions.addWidget(window.remove_engine_button); speech_form.addRow(speech_actions)
        tabs.addTab(speech, "Speech recognition")
        subtitles = QWidget(); subtitle_form = QFormLayout(subtitles); subtitle_form.addRow("Characters per line", window.max_chars); subtitle_form.addRow("Lines per block", window.max_lines)
        subtitle_form.addRow("Minimum duration", window.min_duration); subtitle_form.addRow("Maximum duration", window.max_duration); subtitle_form.addRow("Maximum reading speed", window.max_cps); subtitle_form.addRow(window.restore_defaults_button); tabs.addTab(subtitles, "Subtitles")
        output = QWidget(); output_layout = QVBoxLayout(output); output_layout.addWidget(QLabel("Save folder and package output")); output_layout.addWidget(window.advanced_output_value); output_layout.addWidget(window.advanced_change_output_button); output_layout.addStretch(1); tabs.addTab(output, "Output")
        actions = QDialogButtonBox(QDialogButtonBox.Close); all_defaults = QPushButton("Restore all defaults"); all_defaults.setObjectName("ghostAction"); all_defaults.clicked.connect(window.restore_all_defaults); actions.addButton(all_defaults, QDialogButtonBox.ResetRole); actions.rejected.connect(self.close); layout.addWidget(actions)


def build_production_workspace(window) -> None:
    window.setWindowIcon(QApplication.windowIcon())
    window.setWindowTitle("LARP Audio")
    window.resize(1360, 860)
    window.setMinimumSize(1100, 760)
    root = QWidget()
    page = QVBoxLayout(root)
    page.setContentsMargins(30, 18, 30, 22)
    page.setSpacing(0)

    window.start_over_button = QPushButton("Start over")
    window.start_over_button.setObjectName("navAction")
    window.start_over_button.clicked.connect(window.start_over)
    window.advanced_settings_button = QPushButton("Advanced Settings")
    window.advanced_settings_button.setObjectName("navAction")
    window.about_button = QPushButton("About")
    window.about_button.setObjectName("navAction")
    window.about_button.clicked.connect(window.show_about)
    header = MainHeader(
        window.start_over_button,
        window.advanced_settings_button,
        window.about_button,
    )
    window.status_badge = header.status_badge
    page.addWidget(header)
    page.addWidget(Hairline())
    page.addWidget(WorkflowStrip())

    window.error_frame = QFrame()
    window.error_frame.setObjectName("processingCard")
    error_layout = QHBoxLayout(window.error_frame)
    window.error_label = QLabel()
    window.error_label.setObjectName("errorBanner")
    window.error_label.setWordWrap(True)
    window.copy_error_button = QPushButton("Copy details")
    window.dismiss_error_button = QPushButton("Dismiss")
    window.copy_error_button.clicked.connect(window.copy_error_details)
    window.dismiss_error_button.clicked.connect(window.controller.dismiss_failure)
    error_layout.addWidget(window.error_label, 1)
    error_layout.addWidget(window.copy_error_button)
    error_layout.addWidget(window.dismiss_error_button)
    page.addWidget(window.error_frame)

    inputs = QSplitter(Qt.Horizontal)
    inputs.setChildrenCollapsible(False)
    inputs.setHandleWidth(18)
    audio = SurfaceCard("Voiceover", kicker="Audio")
    window.audio_card = audio
    audio.setProperty("interactive", True)
    audio.setAttribute(Qt.WA_Hover, True)
    audio.setMinimumWidth(315)
    audio.setMaximumWidth(390)
    window.audio_value = ElidedPathLabel("Choose a voiceover audio file")
    window.audio_value.setObjectName("audioFileName")
    window.audio_value.setAlignment(Qt.AlignCenter)
    window.audio_preflight_status = QLabel("Your audio stays on this device")
    window.audio_preflight_status.setObjectName("tiny")
    window.audio_preflight_status.setAlignment(Qt.AlignCenter)
    window.audio_preflight_status.setWordWrap(True)
    audio.body.addStretch(1)
    icon_row = QHBoxLayout()
    icon_row.addStretch(1)
    icon_row.addWidget(WaveformIcon())
    icon_row.addStretch(1)
    audio.body.addWidget(window.audio_value)
    audio.body.addLayout(icon_row)
    audio.body.addWidget(window.audio_preflight_status)
    audio.body.addStretch(1)
    audio_actions = QHBoxLayout()
    window.browse_audio_button = QPushButton("Upload audio")
    window.browse_audio_button.clicked.connect(window.choose_audio)
    window.remove_audio_button = QPushButton("Remove")
    window.remove_audio_button.setObjectName("ghostAction")
    window.remove_audio_button.clicked.connect(window.remove_audio)
    audio_actions.addWidget(window.browse_audio_button)
    audio_actions.addWidget(window.remove_audio_button)
    audio_actions.addStretch(1)
    audio.body.addLayout(audio_actions)

    script = SurfaceCard("Exact text", kicker="Original script")
    window.script_editor = QPlainTextEdit()
    window.script_editor.setPlaceholderText("Paste the exact voiceover script here")
    window.script_editor.setMinimumHeight(220)
    window.script_editor.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    window.script_editor.textChanged.connect(window._script_edited)
    window.script_input_splitter = QSplitter(Qt.Vertical)
    window.script_input_splitter.setChildrenCollapsible(False)
    window.script_input_splitter.addWidget(window.script_editor)
    window.script_input_splitter.setSizes([280])
    script.body.addWidget(window.script_input_splitter, 1)
    script_actions = QHBoxLayout()
    window.script_counter = QLabel("0 characters · 0 words")
    window.script_counter.setObjectName("tiny")
    window.load_script_button = QPushButton("Upload script")
    window.clear_script_button = QPushButton("Clear")
    window.clear_script_button.setObjectName("ghostAction")
    window.load_script_button.clicked.connect(window.choose_script)
    window.clear_script_button.clicked.connect(window.clear_script)
    script_actions.addWidget(window.script_counter, 1)
    script_actions.addWidget(window.load_script_button)
    script_actions.addWidget(window.clear_script_button)
    script.body.addLayout(script_actions)
    inputs.addWidget(audio)
    inputs.addWidget(script)
    inputs.setSizes([355, 900])
    page.addWidget(inputs, 3)
    page.addSpacing(11)
    window.full_input_panel = inputs

    pause_card = QFrame()
    pause_layout = QHBoxLayout(pause_card)
    pause_layout.setContentsMargins(0, 0, 0, 0)
    pause_layout.setSpacing(0)
    window.pause_button_group = QButtonGroup(window)
    window.pause_button_group.setExclusive(True)
    window.pause_preset_buttons = {}
    descriptions = (
        ("tight", "01", "Tight", "Fastest pacing"),
        ("balanced", "02", "Balanced", "Natural short-form pacing"),
        ("natural", "03", "Natural", "More breathing room"),
    )
    for key, number, name, description in descriptions:
        choice = EditorialPauseChoice(number, name, description)
        choice.button.clicked.connect(
            lambda _checked=False, value=key: window.set_pause_preset(value)
        )
        window.pause_button_group.addButton(choice.button)
        window.pause_preset_buttons[key] = choice.button
        pause_layout.addWidget(choice, 1)
    window.custom_preset_label = QLabel("CUSTOM · Advanced Settings")
    window.custom_preset_label.setObjectName("kicker")
    window.custom_preset_label.hide()
    pause_layout.addWidget(window.custom_preset_label)
    page.addWidget(pause_card)
    page.addSpacing(10)
    window.pause_style_card = pause_card

    setup = QFrame()
    setup.setObjectName("setupBar")
    setup_layout = QHBoxLayout(setup)
    setup_layout.setContentsMargins(18, 10, 14, 10)
    setup_layout.setSpacing(24)
    model_block = QVBoxLayout()
    model_block.setSpacing(2)
    window.browse_model_button = QPushButton("SPEECH MODEL" if window.developer_mode else "SPEECH ENGINE")
    window.browse_model_button.setObjectName("setupLabelAction")
    window.browse_model_button.clicked.connect(window.choose_model)
    window.model_value = ElidedPathLabel("Choose local model" if window.developer_mode else "Managed automatically")
    window.model_value.setObjectName("statusText")
    window.model_status = QLabel("Not ready")
    window.model_status.setObjectName("tiny")
    model_block.addWidget(window.browse_model_button)
    model_block.addWidget(window.model_value)
    model_block.addWidget(window.model_status)
    setup_layout.addLayout(model_block, 1)
    output_block = QVBoxLayout()
    output_block.setSpacing(2)
    window.browse_full_output_button = QPushButton("SAVE LOCATION" if window.developer_mode else "RESULTS")
    window.browse_full_output_button.setObjectName("setupLabelAction")
    window.browse_full_output_button.clicked.connect(window.choose_output_directory)
    window.full_output_value = ElidedPathLabel("Choose result folder" if window.developer_mode else "Documents / LARP Audio Results")
    window.full_output_value.setObjectName("statusText")
    output_block.addWidget(window.browse_full_output_button)
    output_block.addWidget(window.full_output_value)
    output_block.addStretch(1)
    if not window.developer_mode:
        window.browse_full_output_button.setEnabled(False)
    setup_layout.addLayout(output_block, 1)
    window.readiness_label = QLabel("NOT READY")
    window.readiness_label.setObjectName("readinessBlocked")
    setup_layout.addWidget(window.readiness_label)
    window.cancel_button = QPushButton("Cancel")
    window.cancel_button.clicked.connect(window.controller.request_cancellation)
    setup_layout.addWidget(window.cancel_button)
    window.process_button = QPushButton("Process")
    window.process_button.setObjectName("primaryAction")
    window.process_button.setDefault(True)
    window.process_button.clicked.connect(window.start_full_processing)
    setup_layout.addWidget(window.process_button)
    page.addWidget(setup)
    page.addSpacing(10)
    window.setup_card = setup

    window.processing_card = QFrame()
    window.processing_card.setObjectName("processingCard")
    processing = QVBoxLayout(window.processing_card)
    processing.setContentsMargins(18, 14, 18, 14)
    processing.setSpacing(9)
    processing_top = QHBoxLayout()
    processing_top.addWidget(_title("PROCESSING AUDIO"))
    processing_top.addStretch(1)
    processing_safety = QLabel("Your script stays unchanged")
    processing_safety.setObjectName("tiny")
    processing_top.addWidget(processing_safety)
    processing_top.addSpacing(16)
    window.warning_status = QLabel("0 warnings")
    window.warning_status.setObjectName("tiny")
    processing_top.addWidget(window.warning_status)
    processing.addLayout(processing_top)
    window.status_message = QLabel("Preparing audio")
    window.status_message.setObjectName("kicker")
    processing.addWidget(window.status_message)
    window.progress = QProgressBar()
    window.progress.setRange(0, 0)
    processing.addWidget(window.progress)
    window.processing_events = QListWidget()
    window.processing_events.setObjectName("processingEvents")
    window.processing_events.setFlow(QListView.LeftToRight)
    window.processing_events.setWrapping(False)
    window.processing_events.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    window.processing_events.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    window.processing_events.setMaximumHeight(42)
    processing.addWidget(window.processing_events)
    page.addWidget(window.processing_card)

    window.empty_hint = QFrame()
    window.empty_hint.setObjectName("emptyResult")
    empty_layout = QVBoxLayout(window.empty_hint)
    empty_layout.setContentsMargins(18, 20, 18, 20)
    empty_layout.addWidget(QLabel("RESULT"))
    empty_layout.itemAt(0).widget().setObjectName("kicker")
    empty_layout.addWidget(_title("Nothing processed yet"))
    empty_copy = QLabel("Cleaned audio, subtitle blocks and files will appear here.")
    empty_copy.setObjectName("muted")
    empty_layout.addWidget(empty_copy)
    empty_layout.addStretch(1)
    window.empty_hint.setMinimumHeight(138)
    page.addWidget(window.empty_hint, 2)
    window.success_banner = QLabel("●  RESULT READY")
    window.success_banner.setObjectName("successBanner")
    page.addWidget(window.success_banner)
    export_row = QHBoxLayout()
    export_copy = QLabel("Take the cleaned audio and approved subtitles into your editor.")
    export_copy.setObjectName("muted")
    window.export_button = QPushButton("Export")
    window.export_button.setObjectName("primaryAction")
    window.export_button.setMinimumHeight(44)
    window.export_button.setMinimumWidth(180)
    window.export_button.clicked.connect(window.open_universal_export)
    export_row.addWidget(export_copy)
    export_row.addStretch(1)
    export_row.addWidget(window.export_button)
    window.export_row_widgets = (export_copy, window.export_button)
    page.addLayout(export_row)
    window.result_tabs = QTabWidget()
    window.result_tabs.setAccessibleName("Preview, subtitle blocks, diagnostics and files")
    preview_tab = QWidget()
    preview_layout = QHBoxLayout(preview_tab)
    preview_layout.setContentsMargins(0, 10, 0, 0)
    preview_split = QSplitter(Qt.Horizontal)
    window.preview_block_list = QListWidget()
    window.preview_block_list.setObjectName("previewCueList")
    window.preview_block_list.setAccessibleName("Subtitle blocks for preview")
    window.preview_panel = PreviewPanel()
    preview_split.addWidget(window.preview_block_list)
    preview_split.addWidget(window.preview_panel)
    preview_split.setSizes([360, 720])
    preview_layout.addWidget(preview_split)
    window.result_tabs.addTab(preview_tab, "PREVIEW")
    subtitle_tab = QWidget()
    subtitle_layout = QVBoxLayout(subtitle_tab)
    filter_row = QHBoxLayout()
    filter_row.addWidget(_title("Subtitle blocks"))
    filter_row.addStretch(1)
    window.filter_count_label = QLabel("Showing 0 of 0")
    window.filter_count_label.setObjectName("muted")
    window.show_warnings_only = QCheckBox("Warnings only")
    filter_row.addWidget(window.filter_count_label)
    filter_row.addWidget(window.show_warnings_only)
    subtitle_layout.addLayout(filter_row)
    window.table_model = SubtitleBlockTableModel(window)
    window.warning_proxy = WarningFilterProxyModel(window)
    window.warning_proxy.setSourceModel(window.table_model)
    window.subtitle_table = QTableView()
    window.subtitle_table.setModel(window.warning_proxy)
    window.subtitle_table.setWordWrap(True)
    window.subtitle_table.setSelectionBehavior(QTableView.SelectRows)
    window.subtitle_table.setEditTriggers(QTableView.NoEditTriggers)
    window.subtitle_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
    window.subtitle_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.Stretch)
    window.subtitle_table.verticalHeader().setVisible(False)
    window.show_warnings_only.toggled.connect(window._set_warning_filter)
    subtitle_layout.addWidget(window.subtitle_table)
    window.result_tabs.addTab(subtitle_tab, "SUBTITLE BLOCKS")
    diagnostics_tab = QWidget()
    diagnostics_layout = QVBoxLayout(diagnostics_tab)
    diagnostics_layout.addWidget(_title("Result diagnostics"))
    window.diagnostics_summary = QLabel("Validated metrics will appear here.")
    window.diagnostics_summary.setObjectName("muted")
    diagnostics_layout.addWidget(window.diagnostics_summary)
    window.diagnostics_list = QListWidget()
    diagnostics_layout.addWidget(window.diagnostics_list)
    window.result_tabs.addTab(diagnostics_tab, "DIAGNOSTICS")
    files_tab = QWidget()
    files_layout = QVBoxLayout(files_tab)
    files_layout.addWidget(_title("Files"))
    window.artifact_list = QListWidget()
    files_layout.addWidget(window.artifact_list)
    file_actions = QGridLayout()
    window.open_audio_button = QPushButton("Open cleaned audio")
    window.open_srt_button = QPushButton("Open subtitles")
    window.open_json_button = QPushButton("Open subtitle blocks")
    window.open_zip_button = QPushButton("Open full package")
    window.open_folder_button = QPushButton("Show in folder")
    window.copy_srt_button = QPushButton("Copy subtitle path")
    window.copy_json_button = QPushButton("Copy blocks path")
    window.generate_again_button = QPushButton("Process again")
    window.open_audio_button.clicked.connect(window.open_cleaned_audio)
    window.open_srt_button.clicked.connect(window.open_srt)
    window.open_json_button.clicked.connect(window.open_json)
    window.open_zip_button.clicked.connect(window.open_zip)
    window.open_folder_button.clicked.connect(window.open_output_folder)
    window.copy_srt_button.clicked.connect(window.copy_srt_path)
    window.copy_json_button.clicked.connect(window.copy_json_path)
    window.generate_again_button.clicked.connect(window.start_again)
    file_buttons = (
        window.open_audio_button, window.open_srt_button, window.open_json_button,
        window.open_zip_button, window.open_folder_button, window.copy_srt_button,
        window.copy_json_button, window.generate_again_button,
    )
    for index, button in enumerate(file_buttons):
        file_actions.addWidget(button, index // 4, index % 4)
    files_layout.addLayout(file_actions)
    window.result_tabs.addTab(files_tab, "FILES")
    page.addWidget(window.result_tabs, 2)

    # Technical controls exist only inside the Advanced Settings dialog.
    defaults=SubtitleSettings(); pause_defaults=desktop_mvp_pause_settings(); model_defaults=ModelSettings()
    window.pause_threshold=QDoubleSpinBox(); window.pause_threshold.setRange(-120,-.1); window.pause_threshold.setDecimals(1); window.pause_threshold.setSuffix(" dB"); window.pause_threshold.setValue(float(pause_defaults.silence_threshold_db))
    window.minimum_detected_silence=QSpinBox(); window.minimum_detected_silence.setRange(1,10000); window.minimum_detected_silence.setSuffix(" ms"); window.minimum_detected_silence.setValue(pause_defaults.minimum_pause_duration_ms or 300)
    window.minimum_pause_to_shorten=QSpinBox(); window.minimum_pause_to_shorten.setRange(2,30000); window.minimum_pause_to_shorten.setSuffix(" ms"); window.minimum_pause_to_shorten.setValue(pause_defaults.minimum_pause_to_shorten_ms or 500)
    window.retained_pause=QSpinBox(); window.retained_pause.setRange(1,10000); window.retained_pause.setSuffix(" ms"); window.retained_pause.setValue(pause_defaults.target_remaining_pause_ms or 200)
    window.maximum_pause_removal=QSpinBox(); window.maximum_pause_removal.setRange(1,60000); window.maximum_pause_removal.setSuffix(" ms"); window.maximum_pause_removal.setValue(pause_defaults.maximum_removed_per_pause_ms or 1000)
    window.model_name=QComboBox(); window.model_name.addItems(["tiny","base","small"]); window.device=QComboBox(); window.device.addItems(["cpu","auto","cuda"]); window.compute_type=QComboBox(); window.compute_type.addItems(["int8","auto","float32","float16"]); window.recognition_language=QLineEdit(); window.recognition_language.setPlaceholderText("Automatic"); window.recognition_beam_size=QSpinBox(); window.recognition_beam_size.setRange(1,100); window.recognition_beam_size.setValue(model_defaults.beam_size)
    window.max_chars=QSpinBox(); window.max_chars.setRange(8,200); window.max_chars.setValue(defaults.max_characters_per_line); window.max_chars.setSuffix(" characters"); window.max_lines=QSpinBox(); window.max_lines.setRange(1,4); window.max_lines.setValue(defaults.max_lines); window.max_words=QSpinBox(); window.max_words.setRange(10,10); window.max_words.setValue(defaults.max_words_per_block); window.max_words.hide(); window.min_duration=QSpinBox(); window.min_duration.setRange(100,10000); window.min_duration.setValue(defaults.min_duration_ms); window.min_duration.setSuffix(" ms"); window.max_duration=QSpinBox(); window.max_duration.setRange(100,30000); window.max_duration.setValue(defaults.max_duration_ms); window.max_duration.setSuffix(" ms"); window.max_cps=QDoubleSpinBox(); window.max_cps.setRange(1,100); window.max_cps.setDecimals(1); window.max_cps.setValue(float(defaults.max_characters_per_second)); window.max_cps.setSuffix(" chars / s"); window.restore_defaults_button=QPushButton("Reset subtitle defaults"); window.restore_defaults_button.clicked.connect(window.restore_defaults)
    window.advanced_output_value=ElidedPathLabel("Choose where to save the result"); window.advanced_change_output_button=QPushButton("Change folder"); window.advanced_change_output_button.clicked.connect(window.choose_output_directory)
    window.engine_maintenance_status=QLabel("Managed automatically"); window.check_engine_button=QPushButton("Check"); window.check_engine_button.clicked.connect(window.check_speech_engine); window.repair_engine_button=QPushButton("Repair"); window.repair_engine_button.clicked.connect(lambda: window.prepare_speech_engine(repair=True)); window.remove_engine_button=QPushButton("Remove downloaded data"); window.remove_engine_button.clicked.connect(window.remove_speech_engine)
    window.advanced_dialog=AdvancedSettingsDialog(window); window.advanced_settings_button.clicked.connect(window.advanced_dialog.show)
    for control in (window.pause_threshold,window.minimum_detected_silence,window.minimum_pause_to_shorten,window.retained_pause,window.maximum_pause_removal): control.valueChanged.connect(window._pause_exact_value_changed)

    # Retained hidden compatibility surface for the headless subtitle-only API.
    window.developer_panel=QWidget(); window.developer_panel.hide(); window.alignment_value=ElidedPathLabel(); window.output_value=ElidedPathLabel(); window.browse_alignment_button=QPushButton(); window.browse_alignment_button.clicked.connect(window.choose_alignment); window.browse_output_button=QPushButton(); window.browse_output_button.clicked.connect(window.choose_output_directory); window.output_names=QLabel("subtitle_blocks.json + subtitles.srt"); window.generate_button=QPushButton(); window.generate_button.clicked.connect(window.start_generation); window.summary_list=QListWidget(); window.script_preview=QPlainTextEdit(); window.script_preview.setReadOnly(True); window.advanced_group=QGroupBox(); window.advanced_group.setCheckable(True); window.advanced_group.hide(); window.pipeline_settings_group=QGroupBox(); window.pipeline_settings_group.hide(); window._advanced_widgets=(window.max_chars,window.max_lines,window.max_words,window.min_duration,window.max_duration,window.max_cps,window.restore_defaults_button)

    root.setMinimumWidth(0); root.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
    scroll=QScrollArea(); scroll.setWidgetResizable(True); scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff); scroll.setFrameShape(QFrame.NoFrame); scroll.setWidget(root); window.main_scroll_area=scroll; window.setCentralWidget(scroll)
    window.setTabOrder(window.browse_audio_button, window.script_editor); window.setTabOrder(window.script_editor, window.load_script_button); window.setTabOrder(window.load_script_button, window.pause_preset_buttons["tight"]); window.setTabOrder(window.pause_preset_buttons["natural"], window.browse_model_button); window.setTabOrder(window.browse_model_button, window.browse_full_output_button); window.setTabOrder(window.browse_full_output_button, window.process_button)
    window.set_pause_preset("balanced")
    window.browse_audio_button.setFocus()
